defaults:
  - perceptual_encoder: default
  - plan_proposal: default
  - plan_recognition: default
  - visual_goal: default
  - language_goal: default
  - action_decoder: logistic
  - optimizer: adam

_target_: calvin_agent.models.mcil.MCIL
_recursive_: false

kl_beta: ${loss.kl_beta}
replan_freq: 30
